# Generated by Django 5.2 on 2025-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_equipment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_before_checkin_minutes', models.PositiveIntegerField(default=15, help_text='Số phút trước giờ check-in để gửi thông báo (mặc định: 15 phút).')),
                ('reminder_before_checkout_minutes', models.PositiveIntegerField(default=10, help_text='Số phút trước giờ kết thúc để gửi thông báo (mặc định: 10 phút).')),
            ],
            options={
                'verbose_name': 'Cấu hình thông báo',
                'verbose_name_plural': 'Cấu hình thông báo',
            },
        ),
    ]
