version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - redis
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A BE worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A BE beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app