# Generated by Django 5.2 on 2025-05-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('space_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('MENTORING', 'Mentoring')], default='INDIVIDUAL', max_length=20)),
                ('space_status', models.CharField(choices=[('EMPTY', 'Empty'), ('BOOKED', 'Booked'), ('INUSE', 'In Use')], default='EMPTY', max_length=20)),
            ],
        ),
    ]
