# Generated by Django 5.2 on 2025-05-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspace',
            name='name',
            field=models.CharField(default='Room', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
